# Programming language
language: java

### Maven basic build ###
# Build project, installing to local repo (skip testing and javadoc generation (if those exist))
install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# Test project
script: mvn test -B -V

# Cached directories
cache:
  directories:
  - ~/.m2/repository

# After success scripts
after_success:
# Give required permissions to used shell scripts
- chmod +x ./deploy.sh
- chmod +x ./project-version.sh
- chmod +x ./.travis/deploy.sh
# Deploy to OSSRH repository if possible
- ./deploy.sh